#################################
#             Shadows           #
#################################

shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.3;

#################################
#           Fading              #
#################################

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-delta = 2;

#################################
#   Transparency / Opacity      #
#################################

frame-opacity = 0.8;

#################################
#       General Settings        #
#################################

unredir-if-possible = true;
backend = "glx";
vsync = true;

detect-client-opacity = true;

detect-transient = true;

use-damage = true;

#################################
#            Rules              #
#################################

rules: ({
  match = "class_g = 'dmenu' || class_g = 'slop'";
  shadow = false;
}, {
  match = "focused = false";
  opacity = 0.95;
}, {
  match = "window_type = 'tooltip'";
  fade = false;
  shadow = true;
  opacity = 0.75;
  full-shadow = false;
}, {
  match = "name = 'Notification'   || "
          "class_g = 'Conky'       || "
          "class_g ?= 'Notify-osd' || "
          "class_g = 'Cairo-clock' || "
          "_GTK_FRAME_EXTENTS@";
  shadow = false;
});